project:
  type: book

book:
  title: "Gambling and Statistics"
  author: "Daniel Rogers"
  date: "2025-07-22"
  chapters:
    - index.qmd
    - notation.qmd
    - basic-probability/rolling-dice.qmd
    - basic-probability/flipping-a-coin.qmd
    - basic-probability/problem-of-points.qmd
    - casino-games/roulette.qmd
    - casino-games/craps.qmd
    - casino-games/baccarat.qmd
    - casino-games/blackjack.qmd
    #- poker/texas-hold-em.qmd
    - other-games/index.qmd
    - other-games/chutes-and-ladders.qmd
    - other-games/war.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
  #pdf:
  #  documentclass: scrreprt
  
#ERROR: pdf code above was throwing this error on 2025-08-02:
# tlmgr: Remote database at https://mirrors.mit.edu/CTAN/systems/texlive/tlnet
# (revision 75938 of the texlive-scripts package)
# seems to be older than the local installation
# (revision 75950 of texlive-scripts);
# please use a different mirror and/or wait a day or two.
