<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1 Flipping a Coin (and Basic Probabilities) | Gambling Statistics</title>
  <meta name="description" content="Notes on topics pertaining to gambling and expected outcomes using statistics and computer analysis." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="1 Flipping a Coin (and Basic Probabilities) | Gambling Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Notes on topics pertaining to gambling and expected outcomes using statistics and computer analysis." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1 Flipping a Coin (and Basic Probabilities) | Gambling Statistics" />
  
  <meta name="twitter:description" content="Notes on topics pertaining to gambling and expected outcomes using statistics and computer analysis." />
  

<meta name="author" content="Dan Rogers" />


<meta name="date" content="2020-10-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="problem-of-points.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./index.html">Gambling Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="flipping-a-coin.html"><a href="flipping-a-coin.html"><i class="fa fa-check"></i><b>1</b> Flipping a Coin (and Basic Probabilities)</a><ul>
<li class="chapter" data-level="1.1" data-path="flipping-a-coin.html"><a href="flipping-a-coin.html#overview"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="flipping-a-coin.html"><a href="flipping-a-coin.html#payouts-for-unfair-coins"><i class="fa fa-check"></i><b>1.2</b> Payouts for Unfair Coins</a></li>
<li class="chapter" data-level="1.3" data-path="flipping-a-coin.html"><a href="flipping-a-coin.html#inferring-the-bias-of-a-coin"><i class="fa fa-check"></i><b>1.3</b> Inferring the Bias of a Coin</a><ul>
<li class="chapter" data-level="1.3.1" data-path="flipping-a-coin.html"><a href="flipping-a-coin.html#maximum-likelihood-estimates"><i class="fa fa-check"></i><b>1.3.1</b> Maximum Likelihood Estimates</a></li>
<li class="chapter" data-level="1.3.2" data-path="flipping-a-coin.html"><a href="flipping-a-coin.html#getting-bayesian-with-it"><i class="fa fa-check"></i><b>1.3.2</b> Getting Bayesian With It</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="problem-of-points.html"><a href="problem-of-points.html"><i class="fa fa-check"></i><b>2</b> Problem of Points</a><ul>
<li class="chapter" data-level="2.1" data-path="problem-of-points.html"><a href="problem-of-points.html#overview-1"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="problem-of-points.html"><a href="problem-of-points.html#solution"><i class="fa fa-check"></i><b>2.2</b> Solution</a></li>
<li class="chapter" data-level="2.3" data-path="problem-of-points.html"><a href="problem-of-points.html#inferring-a-players-advantage"><i class="fa fa-check"></i><b>2.3</b> Inferring a Player’s Advantage</a></li>
<li class="chapter" data-level="2.4" data-path="problem-of-points.html"><a href="problem-of-points.html#historical-notes"><i class="fa fa-check"></i><b>2.4</b> Historical Notes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="roulette.html"><a href="roulette.html"><i class="fa fa-check"></i><b>3</b> Roulette</a></li>
<li class="chapter" data-level="4" data-path="craps.html"><a href="craps.html"><i class="fa fa-check"></i><b>4</b> Craps</a><ul>
<li class="chapter" data-level="4.1" data-path="craps.html"><a href="craps.html#dice-odds"><i class="fa fa-check"></i><b>4.1</b> Dice Odds</a></li>
<li class="chapter" data-level="4.2" data-path="craps.html"><a href="craps.html#single-roll-proposition-bets"><i class="fa fa-check"></i><b>4.2</b> Single Roll (proposition) Bets</a><ul>
<li class="chapter" data-level="4.2.1" data-path="craps.html"><a href="craps.html#service-bets"><i class="fa fa-check"></i><b>4.2.1</b> Service Bets</a></li>
<li class="chapter" data-level="4.2.2" data-path="craps.html"><a href="craps.html#ce"><i class="fa fa-check"></i><b>4.2.2</b> C&amp;E</a></li>
<li class="chapter" data-level="4.2.3" data-path="craps.html"><a href="craps.html#field"><i class="fa fa-check"></i><b>4.2.3</b> Field</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="craps.html"><a href="craps.html#multi-roll-bets"><i class="fa fa-check"></i><b>4.3</b> Multi-Roll Bets</a><ul>
<li class="chapter" data-level="4.3.1" data-path="craps.html"><a href="craps.html#big-6-big-8"><i class="fa fa-check"></i><b>4.3.1</b> Big 6 &amp; Big 8</a></li>
<li class="chapter" data-level="4.3.2" data-path="craps.html"><a href="craps.html#hard-way-bets"><i class="fa fa-check"></i><b>4.3.2</b> Hard-Way Bets</a></li>
<li class="chapter" data-level="4.3.3" data-path="craps.html"><a href="craps.html#place-bets"><i class="fa fa-check"></i><b>4.3.3</b> Place Bets</a></li>
<li class="chapter" data-level="4.3.4" data-path="craps.html"><a href="craps.html#buy-bets"><i class="fa fa-check"></i><b>4.3.4</b> Buy Bets</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="craps.html"><a href="craps.html#line-bets"><i class="fa fa-check"></i><b>4.4</b> Line Bets</a><ul>
<li class="chapter" data-level="4.4.1" data-path="craps.html"><a href="craps.html#pass-line"><i class="fa fa-check"></i><b>4.4.1</b> Pass Line</a></li>
<li class="chapter" data-level="4.4.2" data-path="craps.html"><a href="craps.html#pass-odds"><i class="fa fa-check"></i><b>4.4.2</b> Pass odds</a></li>
<li class="chapter" data-level="4.4.3" data-path="craps.html"><a href="craps.html#dont-pass"><i class="fa fa-check"></i><b>4.4.3</b> Don’t Pass</a></li>
<li class="chapter" data-level="4.4.4" data-path="craps.html"><a href="craps.html#dont-pass-odds"><i class="fa fa-check"></i><b>4.4.4</b> Don’t Pass Odds</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="craps.html"><a href="craps.html#summary"><i class="fa fa-check"></i><b>4.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="baccarat.html"><a href="baccarat.html"><i class="fa fa-check"></i><b>5</b> Baccarat</a><ul>
<li class="chapter" data-level="5.1" data-path="baccarat.html"><a href="baccarat.html#overview-2"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="baccarat.html"><a href="baccarat.html#simulation"><i class="fa fa-check"></i><b>5.2</b> Simulation</a></li>
<li class="chapter" data-level="5.3" data-path="baccarat.html"><a href="baccarat.html#card-counting"><i class="fa fa-check"></i><b>5.3</b> Card Counting</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="blackjack.html"><a href="blackjack.html"><i class="fa fa-check"></i><b>6</b> Blackjack</a><ul>
<li class="chapter" data-level="6.1" data-path="blackjack.html"><a href="blackjack.html#introduction-1"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="blackjack.html"><a href="blackjack.html#basic-strategy"><i class="fa fa-check"></i><b>6.2</b> Basic Strategy</a></li>
<li class="chapter" data-level="6.3" data-path="blackjack.html"><a href="blackjack.html#simulation-analysis"><i class="fa fa-check"></i><b>6.3</b> Simulation &amp; Analysis</a><ul>
<li class="chapter" data-level="6.3.1" data-path="blackjack.html"><a href="blackjack.html#expected-returns"><i class="fa fa-check"></i><b>6.3.1</b> Expected Returns</a></li>
<li class="chapter" data-level="6.3.2" data-path="blackjack.html"><a href="blackjack.html#probability-of-blackjack"><i class="fa fa-check"></i><b>6.3.2</b> Probability of Blackjack</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="blackjack.html"><a href="blackjack.html#card-counting-1"><i class="fa fa-check"></i><b>6.4</b> Card Counting</a><ul>
<li class="chapter" data-level="6.4.1" data-path="blackjack.html"><a href="blackjack.html#hilo-count"><i class="fa fa-check"></i><b>6.4.1</b> Hi/Lo Count</a></li>
<li class="chapter" data-level="6.4.2" data-path="blackjack.html"><a href="blackjack.html#acefive-count"><i class="fa fa-check"></i><b>6.4.2</b> Ace/Five Count</a></li>
<li class="chapter" data-level="6.4.3" data-path="blackjack.html"><a href="blackjack.html#continuous-shuffling-machines-csms"><i class="fa fa-check"></i><b>6.4.3</b> Continuous Shuffling Machines (CSMs)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="other-games.html"><a href="other-games.html"><i class="fa fa-check"></i><b>7</b> Other Games</a></li>
<li class="chapter" data-level="8" data-path="chutes-and-ladders.html"><a href="chutes-and-ladders.html"><i class="fa fa-check"></i><b>8</b> Chutes and Ladders</a><ul>
<li class="chapter" data-level="8.1" data-path="chutes-and-ladders.html"><a href="chutes-and-ladders.html#overview-3"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="chutes-and-ladders.html"><a href="chutes-and-ladders.html#markov-processes-and-chains"><i class="fa fa-check"></i><b>8.2</b> Markov Processes and Chains</a></li>
<li class="chapter" data-level="8.3" data-path="chutes-and-ladders.html"><a href="chutes-and-ladders.html#statistics"><i class="fa fa-check"></i><b>8.3</b> Statistics</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="war.html"><a href="war.html"><i class="fa fa-check"></i><b>9</b> War</a><ul>
<li class="chapter" data-level="9.1" data-path="war.html"><a href="war.html#overview-4"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="war.html"><a href="war.html#simulation-1"><i class="fa fa-check"></i><b>9.2</b> Simulation</a></li>
<li class="chapter" data-level="9.3" data-path="war.html"><a href="war.html#results"><i class="fa fa-check"></i><b>9.3</b> Results</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Gambling Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="flipping-a-coin" class="section level1">
<h1><span class="header-section-number">1</span> Flipping a Coin (and Basic Probabilities)</h1>
<div class="figure">
<img src="images/quarter.png" alt="" />
<p class="caption">U.S. Quarter</p>
</div>
<div id="overview" class="section level2">
<h2><span class="header-section-number">1.1</span> Overview</h2>
<p>The simplest game of chance I can imagine is flipping a coin. A fair coin will have a 50% chance of coming up heads and 50% chance of coming up tails. A fair bet is one that pays even money. That means that if you bet $1 on a particular outcome (heads or tails), you win $1 if you’re right and lose $1 if you’re wrong. In gambling terms the <a href="https://en.wikipedia.org/wiki/Odds">“odds”</a> are 1-to-1, meaning there is an equal probability of each outcome, and a fair bet will pay 1-to-1, meaning that the dollar you bet is matched with 1 dollar you win.</p>
<p>The expected value of such a wager is calculated as:</p>
<p><span class="math display">\[ Expected Value = Pr(win) * (\$1) + Pr(lose) * (-\$1) = 0.5 * (\$1) + 0.5 * (-\$1) = \$0 \]</span></p>
<p>This is the basic means of calculating any expectation in statistics. First, you find the probabilities or each event. Next, you multiply each probability by the expected return in each scenario. And then you add those all together. The difficult part is usually finding the probabilities or each outcome, especially in games that involve player’s making choices where you also must work to find the optimal choice in any scenario.</p>
</div>
<div id="payouts-for-unfair-coins" class="section level2">
<h2><span class="header-section-number">1.2</span> Payouts for Unfair Coins</h2>
<p>So what if the coin is not a fair coin and is instead biased towards landing on one side more than the other? If we know the probability of it coming up heads, we can adjust our expectation of a bet on heads. Let’s say we have a 60% chance of getting “heads”. We still bet $1 and win $1 if we’re right. The expected value of our bet is now:</p>
<p><span class="math display">\[ Expected Value = Pr(win) * (\$1) + Pr(lose) * (-\$1) = 0.6 * (\$1) + 0.4 * (-\$1) = \$0.20 \]</span></p>
<p>We can now expect to win $0.20, on average, every time we bet $1 on a flip of the coin.</p>
<p>If both players know this, you won’t find anyone who is willing to take the bet. Instead, they will want to modify the payout to make it a fair game. The payout that does this will be a 3-to-2 bet. This can easily be inferred from knowing that a game with a 60% probability of winning is providing 3-to-2 odds of winning. That is we expect to win 3 times for every 2 times we lose (which is the same as saying we expect to win 60 times for every 40 we lose, but reduced as a fraction to simplest terms). If an event occurs with odds 3-to-2, a fair payout is the inverse: 2-to-3. This means that we have to wager $3 in order to win $2:</p>
<p><span class="math display">\[ Expected Value = 0.6 * (\$2) + 0.4 * (-\$3) = \$0 \]</span></p>
<p>Or if we want to stick with our original bet, we can still wager $1, but the payout if we win will only be 2/3 of that:</p>
<p><span class="math display">\[ Expected Value = 0.6 * (\$1 * 2/3) + 0.4 * (-\$1) = \$0 \]</span></p>
<p>NOTE: Understanding the differences between probabilities of events occurring, the odds of events occurring, and the payouts for different bets are going to be key in our analysis of pretty much any game. Make sure you understand why an event that has a 60% chance of occurring also has 3-to-2 “odds” of occurring. This can be somewhat confusing at first.</p>
</div>
<div id="inferring-the-bias-of-a-coin" class="section level2">
<h2><span class="header-section-number">1.3</span> Inferring the Bias of a Coin</h2>
<div id="maximum-likelihood-estimates" class="section level3">
<h3><span class="header-section-number">1.3.1</span> Maximum Likelihood Estimates</h3>
<p>Inferring the bias of a coin can be as easy or as complex as you would like to make it. The easiest way to estimate the bias of a coin is to flip it a large number of time (maybe a thousand or a million) and record the percentage of times it comes up heads and the percentage of times it comes up tails. The law of large numbers says that in the long run over a large number of trials the overall proportion of events should come increasingly close to their underlying probability of occurring (assuming those probabilities are constant).</p>
<p>But what if you only flip a coin 10 times and observe it come up heads 7 out of those 10 times? Now you are in a tricky spot where you must determine if you truly have enough information from those 10 trials to reliably infer the probability of heads or tails. If we want to estimate the probability of heads in this case, the “maximum likelihood estimate” is 70%. This means that if we assume the probability of heads is 70% and then calculate the likelihood of getting 7 heads and 3 tails in 10 trials, the likelihood will be higher with this estimate of the coin’s bias than with any other estimate. The maximum likelihood estimate for the probability will always be:</p>
<p><span class="math display">\[ Pr(X=x) = \frac{\sum\limits_{n=1}^{N}{(X_n=x)}}{N} \]</span></p>
<p>That is, we count the number of times the event occurs in N trials and express that as a percentage of the total number of trials.</p>
<p>But is this past evidence really enough to say this is the best answer? What if we only have 1 coin flip and it came up heads? The maximum likelihood estimate now is 100% that heads will come up every time. This yields the highest likelihood for our observed data (our 1 trial), but it intuitively is a very bad guess.</p>
</div>
<div id="getting-bayesian-with-it" class="section level3">
<h3><span class="header-section-number">1.3.2</span> Getting Bayesian With It</h3>
<p>The best way to deal with this type of uncertainty is to use Bayesian statistics. These allow us to combine what we have observed in the data with whatever pre-conceived beliefs we might have about the situation. If we believe that a 100% probability of heads is unlikely, we can include that bias in our calculations. We might be wrong, but it will take a large amount of evidence to convince us. The amount of evidence it takes will correlate with how strong our bias is that this should not happen. But even if we start with the belief that the coin will not always flip to heads, if we perform 1,000 trials and see heads every time, we will increasingly become convinced that this is true.</p>
<p>Although it is a powerful way to analyze probabilities, Bayesian methods can be tricky, however, The hardest part is finding a way to quantify your prior expectations mathematically. How sure are you that the coin is likely to be fair? Maybe you distrust the person you are playing against and actually suspect them to have an unfair coin. In that case, how unfair do you think the coin is likely to be? There is no right answer to these questions. They are all subjective. Therefore there is no “correct” way to solve this problem. Every solution depends on our pre-conceived bias or beliefs and the manner in which we choose to quantify those, and it is possible for us to influence the outcome as little or as much as we’d like with those prior beliefs.</p>
<p>There is a good example of what this looks like <a href="https://tinyheero.github.io/2017/03/08/how-to-bayesian-infer-101.html">here</a>, including R code to reproduce the results. On this page they use a discrete set of possibilities that model the probability of flipping heads as either 0%, 10%, 20%, … up to 100%. They start with a triangular probability distribution that favors a 50% probability and rules out the 0% and 100% altogether, setting their probabilities to zero. They then update this prior periodically with new experimental data and show you how the prior probabilities start to evolve. In general, the probability distribution will begin to shift in a way that it begins to favor the maximium likelihood estimator, but in a way that still incorporates our prior beliefs and allows for other possibilities.</p>
<p>In a similar manner, let’s see what happens if we start with a uniform prior, meaning that we have no idea whether the coin is fair or completely biased.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="flipping-a-coin.html#cb1-1"></a>x_values &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.1</span>)  <span class="co"># discrete values we will model</span></span>
<span id="cb1-2"><a href="flipping-a-coin.html#cb1-2"></a>pdf_prior &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span><span class="op">/</span><span class="kw">length</span>(x_values), <span class="kw">length</span>(x_values))</span>
<span id="cb1-3"><a href="flipping-a-coin.html#cb1-3"></a></span>
<span id="cb1-4"><a href="flipping-a-coin.html#cb1-4"></a>avg_value &lt;-<span class="st"> </span><span class="kw">weighted.mean</span>(x_values, pdf_prior)</span>
<span id="cb1-5"><a href="flipping-a-coin.html#cb1-5"></a><span class="kw">print</span>(<span class="kw">paste0</span>(<span class="st">&quot;Expecte Value = &quot;</span>, avg_value))</span></code></pre></div>
<pre><code>## [1] &quot;Expecte Value = 0.5&quot;</code></pre>
<p>As we can see, this simple prior also essentially assumes the coin is fair.</p>
<p>Now, let’s build a function to update our prior based on new data. First, we will need to calculate the likelihood of our data under each of our models (each of our possible values of x):</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="flipping-a-coin.html#cb3-1"></a>get_likelihoods &lt;-<span class="st"> </span><span class="cf">function</span>(x_values, num_heads, num_tails) {</span>
<span id="cb3-2"><a href="flipping-a-coin.html#cb3-2"></a>  <span class="kw">dbinom</span>(num_heads, num_heads<span class="op">+</span>num_tails, x_values)</span>
<span id="cb3-3"><a href="flipping-a-coin.html#cb3-3"></a>}</span></code></pre></div>
<p>Next, we will need to build an update function that applies Bayes’ Theorem:</p>
<p><span class="math display">\[ Pr(\Theta | D) = \frac{Pr(D | \Theta) Pr(\Theta)}{Pr(D)} \]</span></p>
<p>This tells us that the probability of our model (<span class="math inline">\(\Theta\)</span>) given the data (D), can be inferred from the probability (or likelihood) or our data given our model, our prior beliefs about the probability of of the model being right, and the probability of the data itself. In our case, this function will be:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="flipping-a-coin.html#cb4-1"></a>update_priors &lt;-<span class="st"> </span><span class="cf">function</span>(x_values, priors, num_heads, num_tails) {</span>
<span id="cb4-2"><a href="flipping-a-coin.html#cb4-2"></a>  likelihoods &lt;-<span class="st"> </span><span class="kw">get_likelihoods</span>(x_values, num_heads, num_tails)</span>
<span id="cb4-3"><a href="flipping-a-coin.html#cb4-3"></a>  priors &lt;-<span class="st"> </span>(priors <span class="op">*</span><span class="st"> </span>likelihoods) <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(priors <span class="op">*</span><span class="st"> </span>likelihoods)</span>
<span id="cb4-4"><a href="flipping-a-coin.html#cb4-4"></a>  priors</span>
<span id="cb4-5"><a href="flipping-a-coin.html#cb4-5"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="flipping-a-coin.html#cb5-1"></a>trials &lt;-<span class="st"> </span>tibble<span class="op">::</span><span class="kw">tribble</span>(</span>
<span id="cb5-2"><a href="flipping-a-coin.html#cb5-2"></a>  <span class="op">~</span>heads, <span class="op">~</span>tails,</span>
<span id="cb5-3"><a href="flipping-a-coin.html#cb5-3"></a>  <span class="dv">1</span>, <span class="dv">0</span>,</span>
<span id="cb5-4"><a href="flipping-a-coin.html#cb5-4"></a>  <span class="dv">0</span>, <span class="dv">1</span>,</span>
<span id="cb5-5"><a href="flipping-a-coin.html#cb5-5"></a>  <span class="dv">2</span>, <span class="dv">3</span>,</span>
<span id="cb5-6"><a href="flipping-a-coin.html#cb5-6"></a>  <span class="dv">1</span>, <span class="dv">4</span>,</span>
<span id="cb5-7"><a href="flipping-a-coin.html#cb5-7"></a>  <span class="dv">5</span>, <span class="dv">5</span>,</span>
<span id="cb5-8"><a href="flipping-a-coin.html#cb5-8"></a>  <span class="dv">6</span>, <span class="dv">4</span>,</span>
<span id="cb5-9"><a href="flipping-a-coin.html#cb5-9"></a>  <span class="dv">4</span>, <span class="dv">6</span>,</span>
<span id="cb5-10"><a href="flipping-a-coin.html#cb5-10"></a>  <span class="dv">9</span>, <span class="dv">1</span>,</span>
<span id="cb5-11"><a href="flipping-a-coin.html#cb5-11"></a>  <span class="dv">10</span>, <span class="dv">10</span>,</span>
<span id="cb5-12"><a href="flipping-a-coin.html#cb5-12"></a>  <span class="dv">15</span>, <span class="dv">5</span>,</span>
<span id="cb5-13"><a href="flipping-a-coin.html#cb5-13"></a>  <span class="dv">19</span>, <span class="dv">1</span>,</span>
<span id="cb5-14"><a href="flipping-a-coin.html#cb5-14"></a>  <span class="dv">20</span>, <span class="dv">0</span>,</span>
<span id="cb5-15"><a href="flipping-a-coin.html#cb5-15"></a>  <span class="dv">50</span>, <span class="dv">50</span>,</span>
<span id="cb5-16"><a href="flipping-a-coin.html#cb5-16"></a>  <span class="dv">60</span>, <span class="dv">40</span>,</span>
<span id="cb5-17"><a href="flipping-a-coin.html#cb5-17"></a>  <span class="dv">90</span>, <span class="dv">10</span>,</span>
<span id="cb5-18"><a href="flipping-a-coin.html#cb5-18"></a>  <span class="dv">100</span>, <span class="dv">0</span></span>
<span id="cb5-19"><a href="flipping-a-coin.html#cb5-19"></a>)</span>
<span id="cb5-20"><a href="flipping-a-coin.html#cb5-20"></a></span>
<span id="cb5-21"><a href="flipping-a-coin.html#cb5-21"></a>avg_posterior &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="ot">NA_real_</span>, <span class="kw">nrow</span>(trials))</span>
<span id="cb5-22"><a href="flipping-a-coin.html#cb5-22"></a><span class="cf">for</span> (i_row <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(trials)) {</span>
<span id="cb5-23"><a href="flipping-a-coin.html#cb5-23"></a>  pdf_posterior &lt;-<span class="st"> </span><span class="kw">update_priors</span>(x_values, pdf_prior, trials<span class="op">$</span>heads[i_row], trials<span class="op">$</span>tails[i_row])</span>
<span id="cb5-24"><a href="flipping-a-coin.html#cb5-24"></a>  avg_posterior[i_row] &lt;-<span class="st"> </span><span class="kw">weighted.mean</span>(x_values, pdf_posterior)</span>
<span id="cb5-25"><a href="flipping-a-coin.html#cb5-25"></a>}</span>
<span id="cb5-26"><a href="flipping-a-coin.html#cb5-26"></a></span>
<span id="cb5-27"><a href="flipping-a-coin.html#cb5-27"></a>knitr<span class="op">::</span><span class="kw">kable</span>(<span class="kw">data.frame</span>(</span>
<span id="cb5-28"><a href="flipping-a-coin.html#cb5-28"></a>  <span class="dt">n =</span> trials<span class="op">$</span>heads <span class="op">+</span><span class="st"> </span>trials<span class="op">$</span>tails,</span>
<span id="cb5-29"><a href="flipping-a-coin.html#cb5-29"></a>  <span class="dt">heads =</span> trials<span class="op">$</span>heads,</span>
<span id="cb5-30"><a href="flipping-a-coin.html#cb5-30"></a>  <span class="dt">tails =</span> trials<span class="op">$</span>tails,</span>
<span id="cb5-31"><a href="flipping-a-coin.html#cb5-31"></a>  <span class="dt">mle =</span> trials<span class="op">$</span>heads <span class="op">/</span><span class="st"> </span>(trials<span class="op">$</span>heads <span class="op">+</span><span class="st"> </span>trials<span class="op">$</span>tails),</span>
<span id="cb5-32"><a href="flipping-a-coin.html#cb5-32"></a>  <span class="dt">avg_posterior =</span> avg_posterior</span>
<span id="cb5-33"><a href="flipping-a-coin.html#cb5-33"></a>))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">n</th>
<th align="right">heads</th>
<th align="right">tails</th>
<th align="right">mle</th>
<th align="right">avg_posterior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.7000000</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.00</td>
<td align="right">0.3000000</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">0.40</td>
<td align="right">0.4287129</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">0.20</td>
<td align="right">0.2928934</td>
</tr>
<tr class="odd">
<td align="right">10</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0.50</td>
<td align="right">0.5000000</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">6</td>
<td align="right">4</td>
<td align="right">0.60</td>
<td align="right">0.5833635</td>
</tr>
<tr class="odd">
<td align="right">10</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0.40</td>
<td align="right">0.4166365</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">9</td>
<td align="right">1</td>
<td align="right">0.90</td>
<td align="right">0.8180324</td>
</tr>
<tr class="odd">
<td align="right">20</td>
<td align="right">10</td>
<td align="right">10</td>
<td align="right">0.50</td>
<td align="right">0.5000000</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="right">15</td>
<td align="right">5</td>
<td align="right">0.75</td>
<td align="right">0.7273362</td>
</tr>
<tr class="odd">
<td align="right">20</td>
<td align="right">19</td>
<td align="right">1</td>
<td align="right">0.95</td>
<td align="right">0.8782598</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="right">20</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.9870205</td>
</tr>
<tr class="odd">
<td align="right">100</td>
<td align="right">50</td>
<td align="right">50</td>
<td align="right">0.50</td>
<td align="right">0.5000000</td>
</tr>
<tr class="even">
<td align="right">100</td>
<td align="right">60</td>
<td align="right">40</td>
<td align="right">0.60</td>
<td align="right">0.5976159</td>
</tr>
<tr class="odd">
<td align="right">100</td>
<td align="right">90</td>
<td align="right">10</td>
<td align="right">0.90</td>
<td align="right">0.8975115</td>
</tr>
<tr class="even">
<td align="right">100</td>
<td align="right">100</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">0.9999973</td>
</tr>
</tbody>
</table>
<p>We can see that Bayesian updates swing pretty quickly with only 1 observation, moving toward a 70% probability for whichever side of the coin it saw come up first. With more data it starts to go closer to the maximum likelihood estimate. In this case even after 5 flips of the coin we are pretty close to the MLE, 42.8% versus 40% when we see 2 out of 5 come up heads and 29.3% versus 20% when we see 1 out of 4 come up heads. In this case we move quickly towards the MLE because we did not specify a strong preference for any of the models in our prior. We do see that the model is rather unwilling to go too far to the extremes though. When 20 out of 20 trials all turn up heads, it is only willing to go as far as a 98.7% probability of heads, leaving room for tails to still appear on the next toss. Even after 100 out of 100 trials all turn up heads, it still leaves the tiniest probability that tails still might occur.</p>
<p>My brother told me once that he was reading the book “Probability Theory: The Logic of Science” by E.T. Jaynes and that it started with an opening chapter on probabilities for flipping coins. One interesting question Jaynes asked was: what is the probability that the coin will land on its edge and be neither heads nor tails? Now, we might toss a coin a million times and never see these happen, but that doesn’t mean that it is impossible. Jaynes proposed a Bayesian approach that could begin with some assumption about the probability of this event. Perhaps we give it a 1% probability. Then we can run our million tests, update our probabilities, and even if we never see it occur, there will still be a non-zero probability that it could occur on the next roll. This is an interesting way to include potential outcomes in your model even when they have never been witnessed before.</p>
<p>Ultimately, we can be sure of one thing: flipping a coin is not as trivial mathematically as it might first appear. There are all kinds of good statistical lessons that can be learned from this simple experiment.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="problem-of-points.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["gambling-stats.pdf", "gambling-stats.epub"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
